/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.decoder.iridium;

public class iridiumAmbeJNI {

    static {
        boolean embeddedLibrary = EmbeddedLibraryTools.LOADED_EMBEDDED_LIBRARY;
    }

  public final static native long new_Iridium();
  public final static native void delete_Iridium(long jarg1);
  public final static native void Iridium_decode(long jarg1, Iridium jarg1_, byte[] jarg2, int jarg3, byte[] jarg4, int jarg5);
}
