/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.lissen2me;

public class Iridium {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Iridium(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Iridium obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        iridiumAmbeJNI.delete_Iridium(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Iridium() {
    this(iridiumAmbeJNI.new_Iridium(), true);
  }

  public void to_decode(byte[] input, int in_size, byte[] output, int out_size) {
    iridiumAmbeJNI.Iridium_to_decode(swigCPtr, this, input, in_size, output, out_size);
  }

}
